### ISSUE TITLE
자동정리 예정인 회원에게 메일이 발송된 이후...

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#1]
해당 회원이 다시 로그인을 하면 어떻게 처리가 될까요 ?

한달전에 미리 회원에게 안내 메일이 발송이 되었는데요...
정리 날짜인 한 달후에 보니 해당회원이 로그인 이력이 발견된 경우 해당 회원을 별도테이블로 이동이나 삭제가 되면 안될거 같아서요.

**Comment by kijin** [comment]
정리 시점에서 최종 로그인 날짜를 다시 확인하기 때문에, 안내메일 발송 이후 로그인했다면 정리되지 않습니다. (만약 로그인했는데도 정리된다면 로그인하는 의미가 없잖아요.)

**Comment by wookho** [comment]
@kijin 네. 맞습니다. 우문인줄 알지만 무척 궁금해서 질문했어요 ㅋ
