### ISSUE TITLE
회원을 제외할 필요가 있어 보입니다..ㅎ 

### ISSUE THREAD

**Issue by bjrambo** [poesis/xe-member-expire#10]
일부 사이트 기능을 위해서 일부러 관리용으로 쓰는 회원의 경우 로그인하지 않더라도 휴먼계정에 들어가면 안됩니다.

(예를들어서 포인트팡팡을 알려주는 모듈에서 생성한 맴버같은것들요...)
![_081015_060455_am](https://cloud.githubusercontent.com/assets/4381756/9158916/c6c598e2-3f59-11e5-8522-ed9e75019bbb.jpg)

포인트팡팡모듈(애드온을 모듈화시켜서 계정생성도 용의하게 만들어놨었습니다...) 에서 맴버 추가한 계정이라던지..관리용으로 쓰일 예정은 삭제되거나 휴면계정으로 전환이 되지 않아야 합니다..(각각 매 로그인하지 않더라도요..)
혹시 이부분은 제외할 수 있는 옵션으로 제공되었으면 좋겠습니다.
(기왕이면 여러 계정을 쉽게 등록할 수 잇도록 해줬으면 좋겠어요..)

`````` Ex
101,102,103```
이런형태로요..
``````

**Comment by kijin** [comment]
@qw5414 예외 기능을 추가했으니 테스트 부탁드립니다.
