### ISSUE TITLE
휴면계정의 비밀번호 찾기 오류

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#12]
오늘 휴면계정으로 전환된 회원의 요청으로 확인이 되었습니다.
휴면상태에서 비빌번호를 몰라 새로운 비밀번호를 발급받아(이메일로 새로운 비밀번호 수신)  로그인을 시도하면 
비밀번호가 틀리다고 나오며 로그인이 되지 않습니다.

이전 버전에서 패치된 것으로 되어있는데 오류가 있는듯 합니다.

**Comment by kijin** [comment]
혹시 자동 정리 옵션을 꺼놓은 상태에서도 그런 현상이 발생하는지 확인해 주시면 감사하겠습니다.

어느 정도는 패치가 되었는데, 여전히 새 비밀번호를 발급받는 시점과 로그인을 시도하는 시점 사이에 자동 정리 기능이 끼어드는 현상이 남아있지 않나 의심이 됩니다. 만약 문제가 지속된다면 #10 이슈를 처리하면서 최근에 새 비밀번호를 발급받은 휴면회원을 임시로 예외지정하는 방법으로 해결할 수 있을 것 같습니다.

**Comment by wookho** [comment]
제가가 본 바로는 휴면전환된 계정의 경우  비밀번호를 새로 발급받았을때 이 비밀번호가 메일로 전송은 되지만 db에 새로운 비밀번호가 저장되지 않아 비밀번호가 일치하지 않는 것으로 보입니다.

제가 테스트를 할 수있는  계정이 없어서 어떻게 테스트를 해야할지 모르겠네요.
메일 계정이 남는게 없어서요.

**Comment by kijin** [comment]
아, 그럴 수도 있겠네요. 임시로 되돌려 놓으면서 캐싱 때문에 예전 데이터가 저장되는 건가...

제가 테스트 계정을 잔뜩 만들어서 양쪽 가능성을 모두 테스트해 보겠습니다.

**Comment by wookho** [comment]
아.. 새로운 비밀번호를 발급 받으면 보이진 않지만 임시로 복원을 잠시 하는 방법이 사용되는거군요. 
테스트를 해드리지 못해 죄송하네요.

**Comment by kijin** [comment]
네, 비번 리셋은 아무나 할 수 있지만 실제로 메일을 받고 링크를 클릭해야 인증에 성공하는 것이기 때문에, 비번 리셋 메일을 발송하는 단계에서는 계정을 정식으로 복원하지 않고 임시 복원만 합니다.

아무튼 연휴가 끝나야 자세히 살펴볼 수 있을 것 같습니다. 며칠만 기다려 주세요.

**Comment by kijin** [comment]
임시로 복원했다가 다시 원위치시키는데, 이 때 캐싱된 데이터를 사용하는 바람에 비번 변경이 적용되지 않는 문제가 있었네요. 1.2 버전에서는 캐싱을 사용하지 않도록 하여 해결했습니다.
