### ISSUE TITLE
휴면계정과 탈퇴계정의 차이를 구분할 수 있을까요?

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#14]
문서열람 페이지에서 휴면계정과 탈퇴계정을 안내하고 싶은데요.

지금 휴면계정과 탈퇴계정의 차이가 그룹아이콘의 유무로 확인할 수는 있습니다. 다만 직관적으로 휴면계정입니다, 탈퇴계정입니다 라고 출력을 해주고 싶습니다.

문서열람페이지에서 어떤 구문을 삽입해서 가능할지 알고 싶네요. 
시간이 허락되신다면 한번 살펴봐주시면 감사하겠습니다.

**Comment by kijin** [comment]
정보통신망 이용촉진 및 정보보호 등에 관한 법률 시행령 제16조의 3

> 정보통신서비스 제공자등은 제2항에 따라 개인정보를 별도로 저장·관리하는 경우에는 법 또는 다른 법률에 특별한 규정이 있는 경우를 제외하고는 해당 개인정보를 이용하거나 제공하여서는 아니 된다.

글을 읽을 때 특정인이 휴면회원이라는 사실을 공개적으로 표시하는 것이 "이용" 또는 "제공"에 해당하는지 따져봐야겠네요. 법의 취지는 사실상 탈퇴한 것과 똑같이 취급하라는 것 같은데...

일단 게시판 스킨에서는 (1) 그룹아이콘이 존재하지만 (2) `member_srl`과 일치하는 회원이 실제로 존재하지는 않는 경우, 휴면회원으로 판단할 수 있겠습니다. 둘 다 존재하면 정상회원이고, 둘 다 없다면 탈퇴한 거죠. 그러나 실제로 회원이 존재하는지 파악하려면 한 번 더 쿼리를 해야 하기 때문에 서버에 부담이 발생할 수도 있어요. 그룹아이콘이 남아 있는 것도 이 모듈의 구현 방식 때문에 나타나는 부작용일 뿐, 사실 정상적인 현상은 아니고요.

**Comment by wookho** [comment]
휴면사실을 알리는 것도 문제가 될 수 있군요. 그럼 차라리 휴면과탈퇴의 회원을 그냥 합쳐서 명기하도록 해야 겠네요. 감사합니다.
