### ISSUE TITLE
별도저장회원 삭제시 즉시 반영이 되었으면 합니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#15]
모듈개발초기 확인되었던 정상회원 -> 휴면(별도저장) 으로 전환될때 캐시파일재생성을 해야 반영이 되었던 문제는 조치를 해 주셨었는데요.

별도저장회원  -> 삭제 처리시에도 비슷한 처리가 필요할 듯 합니다.

별도저장회원으로 이동된 계정을 삭제처리 하게 되면  해당회원을 불러오는 곳에서 여전히 탈퇴하지 않고 휴면으로 되어있는 회원으로 불러옵니다. 캐시파일 재생성을 해주면 탈퇴된 회원으로 보여지구요.
(ex:저희 사이트는 그룹아이콘을 사용하는데 탈퇴시 그룹아이콘이 없어지는 것으로 확인이 가능합니다.)

**Comment by kijin** [comment]
1.2.1 버전에서 캐시 갱신 기능이 강화되었습니다. 여전히 문제가 있는지 확인 부탁드립니다.

**Comment by wookho** [comment]
요 이슈는 저희 사이트는 동일하네요. 스스로 탈퇴한 경우와 관리자가 회원목록에서 삭제할 경우는 정상적으로 탈퇴한 회원으로 처리가 됩니다.

휴면계정정리모듈에서 정리대상회원을 삭제시에는 아직 휴면회원인 것 처럼 처리가 되네요. 캐시파일 재생성하기 전에는요. 요건 제가 어차피 매일 하는 일이라 회원들 삭제 후에 캐시재생성은 한번씩 해주면 되니 그렇게 처리하도록 하겠습니다. 혹시 나중에 처리 가능하면 그때 부탁드립니다.

**Comment by kijin** [comment]
혹시 object cache를 어떤 것으로 사용하고 계신가요? (예: memcache)

**Comment by wookho** [comment]
저희는 apc 를 사용하고 있습니다. 그런데 문제는 일반적인 회원탈퇴시에는 반영이 잘 되고 있어요.

**Comment by kijin** [comment]
혹시 최신 커밋으로 업데이트해도 같은 문제가 발생하는지 확인해 주실 수 있을까요? 제 테스트 서버에서는 그룹아이콘이 확실히 없어지도록 만드는 데 성공했습니다만...

**Comment by wookho** [comment]
최신버전으로 방금 설치하고 이제 삭제 즉시 확인해 보면 탈퇴회원으로 잘 나옵니다. 그룹아이콘 없어지고 다른 탈퇴회원과 동일하게 되었습니다. 감사합니다. 이슈는 닫으셔도 될 듯 합니다.

**Comment by kijin** [comment]
잘 된다니 다행이네요. 곧 정리해서 1.2.2 버전으로 올리겠습니다.
