### ISSUE TITLE
별도저장회원 리스트에서 회원그룹이 보였으면 좋겠습니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#16]
저희 사이트의 경우 준회원은 삭제시 아무조치를 하지 않아도 되기 때문에 
현재 삭제시 대상회원의 회원그룹을 조회해서 준회원이면 즉시 삭제 준회원이 아닌 활동이력이 있는 정회원 이상은 사용금지닉네임에 해당 닉네임을 추가해 주는 작업을 해주고 있습니다.

회원그룹이 목록에서 보여지면 준회원들을 빠르게 삭제해 주고 나머지 대상회원은 금지닉네임에 닉네임 넣어주는 작업을 빠르게 진행할 수 있어서요.

대상을 분류할때 그룹으로 분류가 필요한 사이트는 더 있을 것으로 생각됩니다.

**Comment by kijin** [comment]
라이믹스에서 수시로 날아오는 알림에 파묻혀서 이제야 확인했네요 ㅠ

이 모듈은 한동안 업데이트를 하지 않았는데, 다음 버전에서는 회원 그룹도 표시해 드리도록 하겠습니다.

**Comment by kijin** [comment]
1.2.1 버전에서 모든 회원 목록에 그룹 정보를 표시하도록 변경하였습니다.
