### ISSUE TITLE
회원정리 관련 문의..

### ISSUE THREAD

**Issue by bjrambo** [poesis/xe-member-expire#17]
일딴 날자가 애매하니 오늘날자를 기준으로 설명드릴께요.

설정조건,
정리를 5월 31일에 한다하고, 오늘 만약 메일을 발송하게됩니다.
휴면계정 판단조건은 1년인데 만약 메일발송에서 이런 문제가 잇을것같아요.

5월 31일에 정리할거라는 통보를 일주일 이전인 5월 24일에 발송하게 되는데 작년5월24일에서 5월 31일까지 동안에 휴면계정 판단조건에 들어오는 인원이 더 생기기 마련입니다.

혹시 이 경우 휴면계정 판단조건에 따라 설정한 정리일에 맞게 5월 31일까지의 기준으로 1년에 포함되는지 궁금해요. 만약 안된다면 그 사이 메일통보도 없이 삭제되는 회원이 있을거라 생각합니다. 이 경우를 생각해서 발송할 내용이 필요합니다.

**Comment by kijin** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/164058/15496522/a4fcedaa-21d0-11e6-97be-ffaceaacdbac.png)

**Comment by bjrambo** [comment]
아하!(?)

**Comment by bjrambo** [comment]
자동옵션을 사용하지 않음 상황에서 다음과 같은 에러가 뜨네요.

```
현재 휴면계정 수가 너무 많습니다. 자동 정리 또는 안내메일 자동 발송 옵션을 사용하려면 우선 휴면계정을 일괄 정리해 주십시오.
```

안내메일 자동발송이 아니라, 현재부터 시작하는 단계로 (자동메일이나 자동정리기능을 사용하지 않을예정 앞으로도..) 상태에서는 어떻게 안되나요?

**Comment by kijin** [comment]
5월 24일 - 통보메일 일괄 발송
5월 31일 - 휴면계정 일괄 정리
6월 1일 - 자동정리 옵션을 켜고 6월 8일부터 정리하도록 설정
6월 1일 - 안내메일 자동 발송을 7일 전으로 설정

**Comment by bjrambo** [comment]
그럼 지금부터 5월31일까지 접속하지 않은 유저들에게는 일괄발송이 안되나요?ㅠㅠ

**Comment by bjrambo** [comment]
자동옵션은 안킬거같은데..T^T
흐음..

**Comment by kijin** [comment]
안내메일 자동 발송을 켜두면 일괄 발송할 때도 그 기간만큼 미리 더해서 발송해 주는데, 휴면계정이 너무 많아서 켤 수 없는 상황이라면 이런 문제가 생기는군요 ㅡ.ㅡ

expire_threshold를 372일(365일+7일)로 강제 지정해 놓고 안내메일을 발송한 후, 365일로 바꿔서 일괄 정리하는 방법은 있겠습니다.

**Comment by bjrambo** [comment]
@kijin 어떤방향이라도 그분들에게 메일만 전송할수만있다면..T^T

**Comment by kijin** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/164058/15497872/d01e6aca-21d7-11e6-8aba-8ed400b2a9e6.png)

안내메일 발송할 때 며칠분을 추가로 보낼지 커스터마이징 가능!!!

**Comment by bjrambo** [comment]
:+1:
