### ISSUE TITLE
업데이트 후 그룹표시 부분 반복출력 현상이 있습니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#18]
정회원, 정회원, 정회원, 정회원, 정회원, 정회원, 정회원

이런식인데요. 어떤 회원은 한번만 출력되고 또 어떤 회원은 2번 또 어떤 회원은 위와같이 굉장히 많은 숫자로 반복되어 출력이 됩니다.

**Comment by kijin** [comment]
어떤 회원은 그룹이 중복으로 등록되어 있는 모양이네요. 한 번만 표시하도록 변경하겠습니다.

**Comment by wookho** [comment]
그룹이 중복으로 되어있지 않아요. 그냥 정회원에 소속된 회원인데 저렇게 반복해서 출력됩니다. 그런데 출력횟수의 기준이 뭔지는 모르겠어요. 
정회원,관리그룹 이렇게 소속되어있다면 말씀하신 중복으로 등록되어 있는 경우가 될 거구요.

**Comment by kijin** [comment]
아마 DB에는 정회원, 정회원, 정회원 이렇게 중복으로 등록되어 있을 거예요. 회원모듈에서는 중복된 걸 제거하고 하나만 표시하는 함수를 쓰고 있고요... 그런데 여러 번 쿼리하지 않고 한방에 불러오는 함수가 있길래 써봤더니 이 모양입니다. 엄연히 코어에 있는 함수인데 저밖에 안 쓰는 듯 ㅡ.ㅡ

**Comment by kijin** [comment]
Fixed in c0ddce2

**Comment by wookho** [comment]
감사합니다. 한번만 출력이 잘됩니다.
