### ISSUE TITLE
별도저장회원 삭제시 기존레벨 유지

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#19]
최근 코어에서 탈퇴 삭제회원의 포인트와 레벨 관련자료가 초기화? 되게 되었는지 관리자페이지의 회원목록에서 삭제한 경우 레벨이 0으로 표시되는 것을 확인했습니다.

그런데 이 모듈의 별도저장회원 목록에서 삭제를 하면 가지고 있던 레벨이 회원삭제 이후에도 계속 유지되는 것 같습니다.

**Comment by wookho** [comment]
휴면계정모듈에 의해 삭제된 회원의 경우는 사이트 전역에서 표시되는 닉네임옆에 레벨아이콘의 레벨이 삭제전 레벨을 유지합니다.

최근 코어 패치 후 회원리스트에서 삭제된 회원의 경우는 이렇지 않고 레벨이 0으로 조정되어 보이더라구요.

**Comment by kijin** [comment]
제 테스트로는 관리자가 회원목록에서 직접 삭제한 회원도 레벨이 그대로 나옵니다. XE 최신버전의 소스를 뒤져봐도 탈퇴 또는 관리자가 삭제한 회원의 포인트 정보를 초기화하는 기능은 보이지 않고요. xe_point 테이블과 files/member_extra_info/point 폴더의 캐시파일도 모두 그대로 남는 것을 확인했습니다.

**Comment by wookho** [comment]
아 그럼 제가 잘못 판단 한것 이군요. 최근 물의를 일으킨 회원을 제가 관리자 회원목록에서 삭제를 한 후  이 회원의 글등에서 레벨이 0으로 표시되어 최근 코어 업데이트시 변화가 있었던 것으로 생각했습니다.
여전히 기존레벨을 유지한다면 검토가 아직 필요하지 않는 단계이네요.

이 회원이 레벨0으로 된건 그럼 미스테리이네요. 잘 알겠습니다.

**Comment by kijin** [comment]
문제를 일으킨 회원을 차단하거나 정지시키는 과정에서 다른 모듈이나 애드온의 작용으로 포인트가 초기화되었는지도 모르겠네요.

아무튼 XE 코어에서는 회원 삭제시 포인트를 건드리지 않으므로 휴면계정 모듈에서도 그대로 따르고 있습니다. 코어의 정책이 변경된다면 여기서도 변경할게요.

**Comment by wookho** [comment]
일단 나중에 코어에서 이부분이 반영된다면 다시 문의 드리겠습니다. 감사합니다.
