### ISSUE TITLE
자동정리시작 일시

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#2]
8월 18일로 고정되어 있고 변경이 되지 않는데요. 이게 의도된 것인지요 ?

**Comment by wookho** [comment]
저희 사이트에서 일부 서드파티의 자료들 중에 달력피커가 활성화가 안되는 사례가 있습니다. 저는 이게 코어 문제일듯 한데요..

Uncaught TypeError: $(...).datepicker is not a function

**Comment by kijin** [comment]
![untitled](https://cloud.githubusercontent.com/assets/164058/8921688/401ae58a-3514-11e5-8af9-dec73c7f0b28.PNG)

스샷과 같이 변경되어야 정상입니다. 역시 datepicker 오류인 것 같네요. 이건 코어 문제인데... ㅠㅠ

**Comment by wookho** [comment]
/**
         \* 설정 화면 날짜 선택.
         */
        if ($("#auto_start").size()) {
            $("#auto_start_picker").datepicker({
                changeMonth: true,
                changeYear: true,

**Comment by wookho** [comment]
그래서 저희 사이트에서는 피커가 활성화되지 않는 다른 서드파티 프로그램에서는 상단에 피커를 로드하는 문구 두세줄을 넣고 있어요.

**Comment by wookho** [comment]
![-1](https://cloud.githubusercontent.com/assets/6590236/8921726/ca8eada0-3514-11e5-9714-0477ed684deb.jpg)

**Comment by wookho** [comment]
감사합니다. 잘 되네요.
