### ISSUE TITLE
member_expire.model.php 파일에서 PHP오류관련.

### ISSUE THREAD

**Issue by bjrambo** [poesis/xe-member-expire#22]
member_expire.model.php 파일에서 
![_ _ _122616_110929_am](https://cloud.githubusercontent.com/assets/4381756/21473938/c4abc768-cb5b-11e6-9bd6-a92cc1d6deb1.jpg)
이런 오류가 노출되어 보이네요..

아무래도 init 같은 오류같아 보이는데, Model 을 실행하기 위한 클래스지정에서 생기는 오류인것 같아요..

어떻게 수정하면 될까요?

**Comment by kijin** [comment]
생성자에서 부모클래스의 생성자를 호출하지 않는다고 머라카네요.

객체지향 프로그래밍을 할 때 흔히 하는 실수이긴 한데
이 경우에는 부모클래스에 생성자가 없는데요? ㅡ.ㅡ

**Comment by bjrambo** [comment]
그럼 우찌 저 오류를 없앨수 있을까요...? 보통 init메서드로 실행하면 같은역활하면서 실행은 되긴하던데요.. 이건좀 다른걸까요?

**Comment by kijin** [comment]
PHP 오류는 아니니 아무래도 님 에디터가 호들갑인 듯...

**Comment by bjrambo** [comment]
phpstorm.. ㅠㅠ ㅋㅋㅋㅋㅋ
