### ISSUE TITLE
자동 정리 설정이 안됩니다.

### ISSUE THREAD

**Issue by gosugoon** [poesis/xe-member-expire#24]
1. 6개월 설정
2. 17/4/1 부터 시작
3. 15일 이내 발송

현재 안내메일을 발송하지 않은 휴면계정 수가 너무 많습니다. 안내메일 자동 발송 기능을 사용하려면 우선 안내메일을 일괄 발송해 주십시오.

라고 뜨네요. 정리할 계정이 0 개 입니다. 너무 많다네요.. 허허..

**Comment by kijin** [comment]
안내메일 자동 발송 기간을 설정하면 6개월(183일)이 아니라 6개월+15일(198일)간 로그인하지 않은 회원 수를 계산하게 됩니다. 이 기준으로 정리할 계정이 50개 이상이면 자동 정리 기능이 켜지지 않습니다. "안내메일 일괄 발송" 화면에서 추가 기간을 15일로 선택하면 해당 계정 갯수를 확인할 수 있습니다.

**Comment by socialskyo** [comment]
저도 같은 오류가 나는것같습니다.
일부러 안내메일을 다 보내고 난 이후에도 


"현재 안내메일을 발송하지 않은 휴면계정 수가 너무 많습니다. 안내메일 자동 발송 기능을 사용하려면 우선 안내메일을 일괄 발송해 주십시오." 라고 나오며

안내메일 자동 발송 설정 옵션 변동이 적용 되지 않습니다.
