### ISSUE TITLE
헷갈려서요.

### ISSUE THREAD

**Issue by socialskyo** [poesis/xe-member-expire#26]
![2017-07-15 10 24 03](https://user-images.githubusercontent.com/6075830/28235399-e2fd1d90-6947-11e7-8926-1152f1ae4572.png)
![2017-07-15 10 24 17](https://user-images.githubusercontent.com/6075830/28235400-e513df42-6947-11e7-96e1-965daaa4d31d.png)

정리대상 기간을 1년으로 설정 해놓았습니다.

헌데, 오늘 보니 정리 대상 회원은 0명이라 나오는데, 안내메일 발송 내역에서 최근 로그인 기록을 보면
 1년 넘게 로그인 안한 회원들이 많이 존재합니다... 

이 분들이 정리 대상에 포함 되었어야 하는게 맞는거죠? 확인좀 부탁 합니다. 초기 처음 공개해주셨을때 기억에는 엄청 잘 되어서 언제부터 이랬는지는 기억이 안나네요(최신 버전 사용중입니다.)

**Comment by kijin** [comment]
안내메일 발송 내역이라면 이미 정리된 회원이나 곧 정리될 예정인 회원이 보일 수도 있습니다. 실제로 해당 회원들이 정리가 되었나요? 아니면 정리 대상인데도 정리가 안 되고 있나요?

**Comment by socialskyo** [comment]
![2017-07-16 12 35 11](https://user-images.githubusercontent.com/6075830/28244339-3f68d2aa-6a23-11e7-82b2-cebbca10917f.png)
![2017-07-16 12 35 16](https://user-images.githubusercontent.com/6075830/28244340-3f70f282-6a23-11e7-97ff-b175fc32ffc8.png)

정리하자면
1. 정리 대상은 819명이라는데...
2. 실제 정리대상 목록에는 0명으로 보입니다

그런데 이메일 발송내역에서 찾은 로그인을 안한 사람으로 보이는 닉네임으로 조회해보니 실제 회원 목록에서는 조회가 되지 않습니다.

결론적으로 이미 정리한 회원도 보이는 거라면 정리 대상 819명..... 이 부분이 의문에 남습니다.

**Comment by kijin** [comment]
"90일"이라고 되어 있는 부분을 바꿔보세요. 만약 이걸 줄였을 때 정리 대상 회원 수가 줄어든다면 현재 정리 대상은 없지만 앞으로 90일 이내에 정리될 회원 수를 보여주는 것입니다.

**Comment by socialskyo** [comment]
네. 알겠습니다. 변동이 있습니다. 감사합니다.
