### ISSUE TITLE
별도저장회원 목록에 검색기능이 필요합니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#3]
닉네임의 변경이 금지된 사이트의 경우 운영자가 특별히 예외적으로 닉네임을 변경해 줄 때가 있는데요.
이때 회원목록에서 닉네임으로 검색하여 사용하지 않는 닉네임이 확인된 경우 해당 닉네임으로 관리자가 변경해 줍니다.

그런데 별도저장된 회원으로 이동된 경우 해당닉네임이 회원목록에서는 조회가 되지 않을 거기 때문에 관리자가 회원목록이 아닌 휴면계정관리모듈의 별도저장된회원의 목록에서 조회를 한번더 해 볼수 있도록 닉네임 등으로 조회 기능이 꼭 필요해 보입니다.

**Comment by wookho** [comment]
뭐. 관리자가 회원가입을 시도해 보는 방법도 차선의 방법이겠습니다.

**Comment by kijin** [comment]
관리자라도 얄짤없이 중복에 걸립니다.

검색은 물론이고, 별도 저장했던 회원을 완전 삭제하는 기능도 만들어야겠네요.

**Comment by wookho** [comment]
회원정보 수정에서 닉네임이 중복되어서 변경이 안된다는 말씀이시군요 ?

**Comment by kijin** [comment]
네, `member.insertMember` 및 `member.updateMember` 트리거를 걸었기 때문에 회원정보 생성이나 변경시 무조건 다 걸립니다.

일단 1.0 버전의 자잘한 버그를 해결하고, 검색 기능은 1.1을 목표로 하겠습니다.

**Comment by wookho** [comment]
@kijin 네. 검색기능은 관리자를 위한 편의기능이기에 우선순위에 밀려도 상관 없는 거 같아요,.
