### ISSUE TITLE
WAS가 여러 대인 경우 이메일이 중복 발생되는 문제

### ISSUE THREAD

**Issue by gaejabong** [poesis/xe-member-expire#32]
여러 대의 서버에서 XE가 운영되고 있고 자동 정리/안내 메일 자동으로 발송이 설정했을 때 이메일이 중복되어 발송되는 현상이 있습니다. 원인은 짐작이 가는데 마땅한 대책이 있을지 모르겠습니다. 따로 Redis queue 같은 것을 이용하지 않고 해결할 수 있는 방법이 있을까요?

**Comment by kijin** [comment]
자동 정리 또는 안내 메일 발송 대상을 불러오는 과정에서 race condition이 발생하겠군요.

로그인/로그아웃 트리거에서 해당 기능을 제거하고, PHP-CLI 스크립트로 작성하여 어느 한 군데에서만 cron으로 실행한다면 문제가 발생하지 않을 것 같습니다. Redis queue까지 동원하는 건 오버고요...

이것 외에도 제가 배포하는 자료들 중 cron을 사용하면 도움이 될 만한 것이 여러 개 있는데, 대개 웹호스팅 환경에서 사용하는 XE의 특성상 극소수의 사이트 외에는 사용이 곤란하여 우선순위에서 밀리고 있습니다. 만약 만들더라도 라이믹스에서 기본적인 틀이 잡혀 있는 cron 지원 기능을 활용하여 라이믹스 전용으로 만들어질 가능성이 높습니다.

**Comment by gaejabong** [comment]
네, 저 같은 경우에는 AWS의 Auto Scaling이 적용되어 있어서 고정된 하나의 서버를 지정하기도 어려운 상황입니다. 물론 이런 경우가 일반적이지는 않지만 PHP-CLI 스크립트 형태 실행되도록 개선이 된다면 방법을 찾아볼 수도 있을 것 같네요.
