### ISSUE TITLE
별도저장된 닉네임의 중복검사

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#4]
1명을 별도저장으로 이동하여 테스트를 해 보았습니다.
회원가입시 닉네임이 사용중인 닉네임으로 필터링이 되지 않네요.

**Comment by wookho** [comment]
현재 사이트에서 가입시 중복된 닉네임을 입력하고 다음 입력으로 넘어가는 순간 중복된 닉네임이면 사용할 수 없다고 필터링이 됩니다.

그런데 별도저장된 회원의 닉네임의 경우 사용 가능한 닉네임으로 아무런 제지가 없네요.

**Comment by kijin** [comment]
아, 실시간 중복검사에서 안 걸리는군요. 해당 act를 트리거에 추가해야겠습니다.

실제 가입을 시도하면 중복에 걸릴걸요?

**Comment by wookho** [comment]
@kijin 실제 가입 진행은 해보지 않았어요. 한번 진행을 해보고 알려드릴까요 ? 그래도 막판에 안된다고 하는 것 보다는 닉네임 입력순간 안된다고 이야기 해주는게 좋겠죠 ?

**Comment by kijin** [comment]
Fixed in 9fccbbb

**Comment by wookho** [comment]
감사합니다! 잘 되네요!
