### ISSUE TITLE
정리회원 대상 목록 잘못된 요청 발생합니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#5]
안내메일 일괄발송 탭  -> 정리회원 대상 목록을 보려면 여기를 클릭 하세요.

여기의 링크를 클릭하면 잘못된 요청이 발생합니다.

https://도메인/xe/index.php?module=admin&act=dispMember_expireAdminList

**Comment by kijin** [comment]
AdminListTargets라고 써야 하는데, 링크를 쓰다 말았네요 ㅡ.ㅡ

메뉴 갯수가 늘어나면서 중간에 다소 리팩토링을 했는데, 그 전의 흔적입니다 ^^
