### ISSUE TITLE
탈퇴자와 별도저장회원의 차이점.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#6]
저희 사이트의 경우 그룹아이콘을 사용합니다.

회원이 탈퇴할 경우 그룹이 없어지고 레벨아이콘이 노출되어 해당회원이 탈퇴를 했음을 금방 알 수 있는데요.

금일 휴면계정 일괄정리를 했습니다. 자동정리 기능을 사용하려구요.
그런데 별도저장으로 이동된 회원의 게시판목록등에서 가입된 회원과 동일하게 그룹아이콘을 가지고 있고 한데요. 

어떤 차이로 인해서 이런 차이가 나는 걸까요 ? 
큰 문제가 아니라면 실질적 활동회원이 아닌 것이 나타나는 것이 더 좋을 수도 있다는 판단이 들어서요.

**Comment by wookho** [comment]
다시 생각해보니 완전 탈퇴자와 잠시 쉬고 있는 휴면계정과 차이가 있는게 더 좋을 듯합니다.

**Comment by kijin** [comment]
복원에 대비하여 소속그룹 정보는 삭제하지 않습니다. 그래서 생기는 현상인 것 같네요.
