### ISSUE TITLE
복원시 필수정보 및 모든 항목이 공란입니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#8]
이메일이 사라지면 해당 회원은 로그인이 불가능할 것 같은데요.

다시 살펴보니 전체가 공란이네요.

**Comment by wookho** [comment]
이상한 점은 db에서 해당회원을 조회해 보면 모든 정보가 있습니다.
그리고 복원된 회원의 회원정보보기도 되지 않네요.

**Comment by kijin** [comment]
DB는 정상인데 화면에 이상하게 표시된다면 캐시 문제일지도 모릅니다.

캐시파일 재생성을 하면 어떻게 되나요?

**Comment by wookho** [comment]
@kijin 이상해서 캐시파일재생성도 해보았는데 해당회원은 마우스로 클릭하면 회원정보보기 같은 것이 되지 않습니다. 레어어가 나타나지 않아요.

회원목록에서 조회하면 있긴한데 수정을 눌러보면 이메일주소며 아무것도 없습니다.

**Comment by wookho** [comment]
@kijin 어.. 방금 캐시재생성 하니 이제 정보가 보입니다.

**Comment by kijin** [comment]
회원정보와 관련된 캐시를 죄다 파악해서 비워주는 기능을 만들어야겠네요.

**Comment by wookho** [comment]
회원이 로그인하여 복원이 되었을시 이게 문제가 되지는 않을까요 ?

**Comment by wookho** [comment]
@kijin 다시한번 반복해 보았더니 캐시재생성을 해주니 정상으로 돌아오네요.

**Comment by wookho** [comment]
지금 현재상태에서 별도저장된 회원이 다시 로그인은 가능한걸까요? 그게 안된다면 현재 많은 회원을 별도저장으로 이동시켜버려서 스스로 복원이 안될 것 같아서요.

**Comment by kijin** [comment]
혹시 `files/config/db.config.php`에서 `use_object_cache` 설정을 해두셨나요?

**Comment by wookho** [comment]
@kijin 네. apc 로 설정되어 있습니다.

**Comment by kijin** [comment]
방금 커밋한 것을 사용해도 같은 현상이 발생하는지 확인 부탁드립니다.

**Comment by wookho** [comment]
@kijin 방금커밋하신 파일 한개만 업로드하여 회원 복원해 보니 바로 정상적인 회원으로 보입니다.

**Comment by wookho** [comment]
@kijin  정리 <--> 복원 반복해도 이상없네요.

**Comment by kijin** [comment]
다행이네요 ^^

회원을 삭제 또는 이동한 후에는 캐시를 비워주도록 했는데, 복원할 때는 그 과정을 생략한 것이 문제였습니다. 삭제할 때 이미 비워 주었으니까 다시 비워줄 필요가 없을 거라고 생각했는데, 삭제한 후에 회원정보가 없어진 상태마저 또다시 캐싱될 줄은 몰랐죠...

**Comment by kijin** [comment]
방금 업데이트한 것으로 한 번만 더 테스트해 주시면 감사하겠습니다.

XE 버전에 따라 `_clearMemberCache()` 메소드가 없는 경우도 있고, 가상 사이트를 사용하는 경우 캐시가 완벽하게 비워지지 않는 경우도 있어서, 이런 경우에도 확실하게 캐시를 싹쓸이하도록 고쳐 보았습니다. 더이상 문제가 없다면 이 이슈는 닫아주세요~

아 그리고 몽실아빠님 덕분에 내일은 미지근한 인스턴트커피 대신 차가운 아이스 아메리카노를 한 잔 마셔봐야겠습니다 ^____^

**Comment by wookho** [comment]
네. 이상없이 정리 복원 모두 이상없네요. 네. 저는 차가운 인스턴트커피를 매일 마십니다 ㅋㅋ
