### ISSUE TITLE
자동메일 발송기능에 궁금한게 있습니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-member-expire#9]
2014-08-25  2015-08-25  2015-07-30 09:35:59

위와같이 정리예정일이 8월 25일 입니다. 그리고 메일발송은 30일전으로 자동으로 해 놓았는데요.
메일이 발송되지 않은 회원이 많아 일괄발송을 했습니다.

8월25일 정리대상의 경우 이미 메일이 발송이 되었어야 하는거 아닌지요.

혹시 정리대상일 당일에 메일이 발송되는게 아닌가 해서 문의 드립니다.

오늘 메일 일괄발송시킨 70여명 중 하나의 샘플입니다.

**Comment by wookho** [comment]
2014-07-30  2015-07-30  2015-07-29 09:02:52

위 내역이 자동으로 보내진 회원의 내역입니다. 어제보내졌는데요. 오늘이 정리예정인 회원입니다. 하루전에 메일이 보내졌습니다. 30일 이전에 자동으로 보내는 설정의 날짜보다 짧아서 보내지지 않고 하루전에 보내진걸까요 ??

자동정리시작일자는 7월 28일로 세팅되어 있습니다.

**Comment by kijin** [comment]
30일 전은 이미 지났기 때문에, 그냥 가능한 빨리 발송합니다. 발송 순서는 더 오래 전에 로그인한 회원에게 먼저 발송되고, 같은 날 로그인했다면 더 오래 전에 가입한 회원에게 먼저 발송됩니다. (로그인 날짜와 가입일까지 똑같다면 랜덤으로 선택합니다.)

따라서 2014년 7월 30일에 마지막으로 로그인한 회원에게 먼저 메일이 발송되고, 2014년 8월 25일에 마지막으로 로그인한 회원에게는 조금 더 늦게 발송되는 것이 정상입니다.

그러나 PHP의 특성상 사용자가 없을 때는 아무런 작업도 할 수가 없어요. 게다가 메일 발송은 설정에 따라 상당히 오래 걸릴 수도 있기 때문에 (예: Gmail SMTP 사용시 1통당 1~2초) 페이지를 로딩할 때마다 1건씩 발송한다면 메일 발송은 빨리빨리 이루어지겠지만, 페이지 로딩 속도가 너무 느려지겠지요.

그래서 사용자들이 비교적 오래 기다려 줄 수 있는 "로그아웃" 트리거가 발생할 때만 메일을 발송하도록 해 두었습니다. 정리대상 회원 수에 비해 로그아웃하는 사용자가 별로 없다면 메일 발송이 원활하게 이루어지지 않으므로 관리자가 일괄 발송해 주어야 합니다. (정리대상이 50건 이상 밀린 경우 자동정리 및 안내메일 발송 옵션을 켤 수 없도록 해둔 이유도 바로 이것입니다.)

만약 메일 발송이 계속 밀린다면 다른 상황에서도 메일을 발송할 수 있도록 해야겠는데, 1초 정도 지연이 발생하더라도 괜찮은 트리거를 찾는 것이 관건입니다. 글쓰기 트리거도 고려해 봤는데, 안 그래도 게시판에 글을 쓸 때 끼어드는 애드온들이 많아서 더 느려지면 곤란할 것 같아 일단 보류 중입니다.

**Comment by wookho** [comment]
아.. 잘알겠습니다.당분간 수동으로 처리해주면 자동으로 처리하는데 문제가 없을거 같네요.
